services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dummyDB
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  technical-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: technical-test-app
    container_name: technical-test-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dummyDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    ports:
      - "8080:8080"

  test-runner:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    container_name: test-runner
    working_dir: /test-app
    volumes:
      - .:/test-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dummyDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    command: mvn test

volumes:
  pg_data: