spring:
  application:
    name: technical-test
  datasource:
    url: jdbc:postgresql://localhost:5432/dummyDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

dummyjson:
  base-url: https://dummyjson.com